apiVersion: apps/v1
kind: Deployment
metadata:
  name: recoit-canbus-data-collector-deployment
  namespace: recoit
  labels:
    name: recoit-canbus-data-collector
spec:
  replicas: 3
  selector:
    matchLabels:
      name: recoit-canbus-data-collector
  template:
    metadata:
      name: recoit-canbus-data-collector
      namespace: recoit
      labels:
        name: recoit-canbus-data-collector
    spec:
      containers:
      - name: recoit-canbus-data-collector
        image: 10.105.34.108/recoit-canbus-data-collector:staging
        imagePullPolicy: IfNotPresent
        workingDir: "/usr/src/app"
        ports:
        - containerPort: 3318
          name: web
        env:
        - name: env
          value: "staging"
        livenessProbe:
          httpGet:
            path: /
            port: web  
