apiVersion: apps/v1
kind: Deployment
metadata:
  name: recoit-backend-deployment
  namespace: recoit
  labels:
    name: recoit-backend
spec:
  replicas: 5
  selector:
    matchLabels:
      name: recoit-backend
  template:
    metadata:
      name: recoit-backend
      namespace: recoit
      labels:
        name: recoit-backend
    spec:
      containers:
      - name: recoit-backend
        image: 10.105.34.108/recoit-backend:staging
        imagePullPolicy: IfNotPresent
        workingDir: "/usr/src/app"
        ports:
        - containerPort: 3000
          name: web
        env:
        - name: env
          value: "staging"
        livenessProbe:
          httpGet:
            path: /
            port: web  
