apiVersion: v1
kind: Service
metadata:
  name: recoit-frontend-service
  namespace: recoit
spec:
  selector:
    name: recoit-frontend
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
