apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: recoit
  name: postgres-data-volume
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgresql