apiVersion: v1
kind: Service
metadata:
  namespace: recoit
  name: postgres
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 31532
  selector:
    app: postgres